### ISSUE TITLE
Does infobip/mobile-messaging-react-native-plugin supports react-native 0.70 version?

### ISSUE THREAD

**Issue by RushikeshFIS** [infobip/mobile-messaging-react-native-plugin#52] opened 2022-10-03 05:28 UTC

**Comment by EZarkhin** [comment] 2022-11-28 12:52
Hello, does it not supported at all on both platforms? 
We got our app on 0.70.3 and Android is working fine, while the iOS ChatScreen component shows a "No connection" banner at the top, and input is disabled

**Comment by riskpp** [comment] 2022-11-28 14:41
hi @EZarkhin could be that the problem isn't connected with the plugin version, please check that iOS registration went successfully (you got push registration id and doesn't have any error logs in the console)
For enabling logging on iOS setup logging:true in the configuration - as in the [example](https://github.com/infobip/mobile-messaging-react-native-plugin/blob/master/Example/App.js#L98)

**Comment by EZarkhin** [comment] 2022-11-28 15:49
@riskpp I got no errors in logs as far as I can see and pushRegistrationId is present in the Installation object

**Comment by EZarkhin** [comment] 2022-11-29 08:34
@riskpp Thank you!
There was my bad, all is working fine.

**Comment by riskpp** [comment] 2023-04-20 09:46
0.70 is supported, closing the issue
https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/8.0.1

**Closed by riskpp** 2023-04-20 09:46 UTC
