### ISSUE TITLE
The following are failing while i run react-native run-ios after integrating with this plugin

### ISSUE THREAD

**Issue by Allenkardic** [infobip/mobile-messaging-react-native-plugin#18] opened 2021-04-09 08:25 UTC
The following build commands failed:
        MergeSwiftModule normal x86_64
        Ld /Users/eogie/Library/Developer/Xcode/DerivedData/stowMobile-cxpdjgrsvggoaqfbvogflbxiirfn/Build/Products/Debug-iphonesimulator/RNScreens/RNScreens.framework/RNScreens normal

**Comment by Allenkardic** [comment] 2021-04-09 08:29
this is the error i am getting

**Comment by Allenkardic** [comment] 2021-04-09 08:30
The following build commands failed:

MergeSwiftModule normal x86_64
Ld /Users/eogie/Library/Developer/Xcode/DerivedData/stowMobile-cxpdjgrsvggoaqfbvogflbxiirfn/Build/Products/Debug-iphonesimulator/RNScreens/RNScreens.framework/RNScreens normal

**Comment by riskpp** [comment] 2021-04-09 10:08
Hi @Allenkardic, could you please provide aditionaly mobile-massaging plugin version, react-native version, Xcode version which you are using.

BR,
Olga

**Comment by Allenkardic** [comment] 2021-04-09 10:46
infobip-mobile-messaging-react-native-plugin: ^3.0.0,
    react-native: 0.63.4,
    Xcode 12.4

**Comment by riskpp** [comment] 2021-04-12 07:01
Hi @Allenkardic, we figured out that the issue is in compatibility with [react-native 0.63.4](https://github.com/itinance/react-native-fs/issues/964). We will try to fix it soon, but before you could use react-native 0.62, just don't forget [comment out Flipper](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/How-to-use-Mobile-Messaging-Plugin-with-React-Native-(v0.62.x))  and change deployment target in Podfile - `platform :ios, '10.0'`

We will inform you about compatibility with react-native 0.63 in this thread.

BR,
Olga

**Comment by riskpp** [comment] 2021-04-12 11:34
@Allenkardic could you please try with new version of plugin [v3.0.2](https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/3.0.2). Just don't forget to comment out Flipper in the Podfile:
```
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
```

BR,
Olga

**Comment by Allenkardic** [comment] 2021-04-12 13:35
ok thank you.

I would do that and get back to you as soon as possible.

**Comment by Aliakwe** [comment] 2021-04-14 09:07
Invariant Violation: Native module cannot be null.
Error: Requiring module "node_modules/infobip-mobile-messaging-react-native-plugin/index.js", which threw an exception: Invariant Violation: Native module cannot be null. 

This error occurs when import  ChatView from infobip-mobile-messaging-react-native-plugin

**Comment by riskpp** [comment] 2021-04-14 10:39
Hi @Aliakwe,
Didn't reproduce this issue, I've run newly created project for version 0.63.4 on iOS successfully with installed plugin and this code in App.js:
```
import {
  mobileMessaging,
  ChatView,
} from 'infobip-mobile-messaging-react-native-plugin';

const App: () => React$Node = () => {
  mobileMessaging.init(
    {
      applicationCode: 'application code',
      ios: {
        notificationTypes: ['alert', 'badge', 'sound'],
      },
      inAppChatEnabled: true,
    },
    () => {
      console.log('MobileMessaging started');
    },
    (error) => {
      console.log('MobileMessaging error: ', error);
    },
  );
  return (
    <>
      <ChatView style={{flex: 1}} sendButtonColor={'#FF0000'} />
    </>
  );
};
```
You could try:
- clean cache (`npm start --reset-cache`)
- do pods cleanup (`pos deintegrate & pod install`) from ios folder
- clean build folder (open Xcode, Product->Clean Build Folder

or please provide more details.

BR,
Olga

**Comment by Aliakwe** [comment] 2021-04-14 10:59
Yeah i tried reproducing the error too so i created a new project version 0.63.4 and installed  infobip-mobile-messaging-react-native-plugin it worked fine. I decided to troubleshoot our application and then i realised that infobip-mobile-messaging-react-native-plugin doesn't work when 
@react-native-firebase/firestore: 10.8.1 is installed.

So i uninstalled @react-native-firebase/firestore and infobip-mobile-messaging-react-native-plugin worked fined.

Then i tried installing @react-native-firebase/firestore again and got the error when i ran pod install.

this is the error:
[!] CocoaPods could not find compatible versions for pod "nanopb":
  In snapshot (Podfile.lock):
    nanopb (= 2.30908.0, ~> 2.30908.0)

  In Podfile:
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 10.8.1, which depends on
      Firebase/CoreOnly (~> 7.6.0) was resolved to 7.6.0, which depends on
        FirebaseCore (= 7.6.0) was resolved to 7.6.0, which depends on
          FirebaseCoreDiagnostics (~> 7.4) was resolved to 7.10.0, which depends on
            nanopb (~> 2.30908.0)

**Comment by riskpp** [comment] 2021-04-15 05:32
@Aliakwe regarding issue with nanopb, you can try what advised in [react-native-firebase issue](https://github.com/invertase/react-native-firebase/issues/3673).

BR,
Olga

**Comment by Aliakwe** [comment] 2021-04-16 12:47
So i did that for my test application and it worked but our main application still gives error. This is me thinking the error doesn't have to do with your package. It is quite strange that when i install this package on our app this error come up though.

I have thus far 
Deleted node module
removed derivedData by running this command:  rm -rf ~/Library/Developer/Xcode/DerivedData
delete Pods and Podfile.lock
deleted node modules and package-lock.json 
Then reinstall all this dependencies but still to no avail.

This error still persists 

The following build commands failed:
        Ld /Users/eogie/Library/Developer/Xcode/DerivedData/stowMobile-cxpdjgrsvggoaqfbvogflbxiirfn/Build/Products/Debug-iphonesimulator/RNScreens/RNScreens.framework/RNScreens normal

**Comment by riskpp** [comment] 2021-04-16 12:59
Hi @Aliakwe, could you please provide the list of your dependencies? May be one of them not updated and still uses 'React' instead of 'React-Core' in their Podspec.

BR,
Olga

**Comment by Aliakwe** [comment] 2021-04-16 13:16
"dependencies": {
    "@gorhom/animated-tabbar": "^2.1.1",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/datetimepicker": "^3.4.3",
    "@react-native-community/google-signin": "^5.0.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-firebase/app": "^10.8.1",
    "@react-native-firebase/auth": "^10.8.1",
    "@react-native-firebase/firestore": "^10.8.1",
    "@react-native-segmented-control/segmented-control": "^2.3.0",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@testing-library/react-native": "^7.1.0",
    "@types/jest": "^26.0.20",
    "dom-serializer": "^1.2.0",
    "infobip-mobile-messaging-react-native-plugin": "^3.0.3",
    "jest-fetch-mock": "^3.0.3",
    "lodash": "^4.17.21",
    "native-base": "^2.15.2",
    "react": "16.13.1",
    "react-hook-form": "^6.15.5",
    "react-native": "0.63.4",
    "react-native-anchor-carousel": "^3.1.2",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-image-cache-hoc": "^2.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal": "^11.7.0",
    "react-native-onboarding-swiper": "^1.1.4",
    "react-native-picker-select": "^8.0.4",
    "react-native-progress": "^4.1.2",
    "react-native-progress-circle": "^2.1.0",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-rename": "^2.7.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.0",
    "react-native-swiper": "^1.6.0-rc.3",
    "react-native-testing-library": "^6.0.0",
    "react-native-vector-icons": "^8.0.0",
    "react-navigation": "^4.4.3",
    "react-navigation-animated-switch": "^0.6.4",
    "react-navigation-fluid-transitions": "^0.3.2",
    "react-navigation-stack": "^2.10.2",
    "react-navigation-tabs": "^2.10.1",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-form": "^8.3.7",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "typescript": "^4.1.3"
  },
  "devDependencies": {
    "@babel/core": "7.12.10",
    "@babel/runtime": "^7.12.13",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "^16.13.1"
  },

**Comment by Aliakwe** [comment] 2021-04-16 13:24
plus this two.
"lottie-ios": "^3.1.8",
"lottie-react-native": "^3.5.0",

**Comment by Aliakwe** [comment] 2021-04-19 14:22
Hello Olga,

Is there any update on this.

Thank you

From: Olga Koroleva ***@***.***>
Reply to: infobip/mobile-messaging-react-native-plugin ***@***.***>
Date: Friday, 16 April 2021 at 13:59
To: infobip/mobile-messaging-react-native-plugin ***@***.***>
Cc: Emmanuel Ogie ***@***.***>, Mention ***@***.***>
Subject: Re: [infobip/mobile-messaging-react-native-plugin] The following are failing while i run react-native run-ios after integrating with this plugin (#18)


Hi @Aliakwe<https://github.com/Aliakwe>, could you please provide the list of your dependencies? May be one of them not updated and still uses 'React' instead of 'React-Core' in their Podspec.

BR,
Olga

**Comment by riskpp** [comment] 2021-04-20 07:27
Hi @Aliakwe 
looks like it's `use_frameworks!` option in podfile, with it even without mobile-messaging plugin, project with your dependencies list failed to run with that error.

You could try to integrate plugin manually - [Manual plugin integration for iOS (in case your dependencies do not support 
 use_frameworks!) ](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60))
 
BR,
Olga

**Comment by riskpp** [comment] 2021-06-01 10:31
Closing it, seems it's answered.

**Closed by riskpp** 2021-06-01 10:31 UTC
